### ISSUE TITLE
Probleme sur des puzzles insolvables mais consideres comme solvables

### ISSUE THREAD

**Issue by ademenet** [moannuo/npuzzle#1]
Jai teste ce puzzle :
```
3
1 2 3
4 5 6
7 8 9
```
Et il passe le test de solvabilite alors qu'il devrait etre insolvable !

**Comment by aderragui** [comment]
9 ? Essaye 0 a la place

2017-05-31 12:33 GMT+02:00 moannuo <notifications@github.com>:

**Comment by ademenet** [comment]
Idem pour des puzzles du type :
```
3
1 2 3
34 34 45
67 78 98
```
et
```
3
0 0 0
0 0 0
0 0 0
```

**Comment by ademenet** [comment]
Oui. Je teste des maps errors et ya des trucs qui passent qui devraient pas mais je vais en regler qqes uns : faire ne sorte de ne pas depasser (size ^ 2 - 1) puis verifier qu'il n'y a pas de doublons

Ça devrait regler une partie des problemes

**Comment by aderragui** [comment]
Ah mais moi tout ca je pensais que c'etait gérer dans le parsing au debut.
Je checker pas tout ça !

**Comment by ademenet** [comment]
ok ok, je pensais que tu le faisais, et comme cetait pas dans les commentaires :P

**Comment by ademenet** [comment]
Je men occupe :)

**Comment by aderragui** [comment]
justement je voulais pas surcharger les fonctions . Une tâche par fonction.
Les petits check de doublon ou de chiffres qui ne sont pas sensé êtres là,
pas sont à faire tout au début dans le parsing, non ? Ou juste après pour
garder le code claire

**Comment by ademenet** [comment]
Ok, cest bon. Jai ajoute ca dans parsing. je ferai un peu de refactorisation apres coup, mais a priori ca marche. Je marque as finished
