### ISSUE TITLE
N'arrive pas a resoudre

### ISSUE THREAD

**Issue by ademenet** [moannuo/npuzzle#2]
On le laisse generer un puzzle >>> il tente de le resoudre >>> mais ne finit jamais ! Il ne tombe pas sur le state goal en fait... Donc soit il y a un probleme dans le test de solvabilite soit il y a un probleme dans l'algo du Astar

la trace pour reproduire
```
Start:  [8 3 2 5 1 6 0 7 4]
--- Generating goal state
Goal:  [1 2 3 8 0 4 7 6 5]
--- Solving puzzle using A-star
--- END of the program
```

**Comment by ademenet** [comment]
Meme chose :
```
Start:  [2 8 7 6 4 3 5 1 0]
--- Generating goal state
Goal:  [1 2 3 8 0 4 7 6 5]
--- Solving puzzle using A-star
--- END of the program
```
```
Start:  [5 8 2 3 0 6 4 7 1]
--- Generating goal state
Goal:  [1 2 3 8 0 4 7 6 5]
--- Solving puzzle using A-star
--- END
```
Bon on a un probleme, je vais refactoriser un peu tout ce quon a fait et regarder dou ca vient

**Comment by aderragui** [comment]
Certains arivent a être résolus ?

2017-06-01 10:40 GMT+02:00 moannuo <notifications@github.com>:

**Comment by ademenet** [comment]
Oui ! quand meme :) Mais je suis en train de voir pour ajouter tous les trucs demande par le sujet pour commencer a debugger. Mais jai peur que ce soit la fonction de solvabilite... Jai pas teste avec leur generateur de puzzle, peut etre que ca fait la meme chose. Dans ce cas ce serait lalgo

**Comment by aderragui** [comment]
C'est peut être la fonction de solvabilite. Si c'est le cas c'est easy a
fix (certainement parce que ya une couille avec le fait que toi tu passe N
alors que moi j'attends N², c'est c'est pas ça, alors soitl'algo est mal
implémenter soit ils racontent de lamerde sur le net concernant la
solvabilité^^)

**Comment by ademenet** [comment]
Apres la solvabilite la plupart du temps sur internet cest pour des goal du genre :
```
1 2 3
4 5 6
7 8 0
```
Donc je me demande si nous cest la meme chose... vu que notre goal est un escargot. Jai du mal a croire que ce soit le meme
Bref je regarde je te tiens au jus

**Comment by aderragui** [comment]
tout depend comment tu deroules le puzzle dude.

il faut justementle "derouler" et pas le "destacker"
un puzzle
a b c
d e f
g h i

devra avoir un goal une dimension : a b c  f i h g d e. et c'est sous
format la qu'il faut le passer a ma fonction de solvabilité

**Comment by ademenet** [comment]
mmmmh, ok, mais genre si tu generes `5 8 2 3 0 6 4 7 1` (le dernier exemple que jai donne) :
```
5 8 2
3 0 6
4 7 1
```
moi jenvoie juste un tableau 1D `5 8 2 3 0 6 4 7 1` a la fonction... Donc que ce soit destacke ou pas je men balance en fait. mais toujours est il que mon algo il mouline et quil trouve pas la solution

**Comment by aderragui** [comment]
C'est ce tableau 1D que tu balanceà la fonction de solvabilité ? Si c'est
le cas, c'est pas bon. Balance lui 5 8 2 6 1 7 4 3 0. La on saura vraiment
si c'est solvable ou pas.

**Comment by ademenet** [comment]
Ah ouais ! Cest pas pratique et cest ecrit nul part !
Faut mettre ca dans les docstring, c'est fait pour ca mec :) Je pensais que je balancais le truc naturellement comme ca et que ca me disait si oui ou non cest solvable. Bon je vais tester

**Comment by aderragui** [comment]
Insolvable ce puzzle...

Le 1 juin 2017 à 11:35, Amine Derragui <amine.derragui.pro@gmail.com> a
écrit :

> C'est ce tableau 1D que tu balanceà la fonction de solvabilité ? Si c'est
> le cas, c'est pas bon. Balance lui 5 8 2 6 1 7 4 3 0. La on saura vraiment
> si c'est solvable ou pas.
>

**Comment by ademenet** [comment]
Donc, jai fait le test : 
j'envoie le tableau `5 8 2 6 1 7 4 3 0` et isSovable me dit qu'il est pas soluble
Donc il faut que je trouve une solution pour derouler le tableau... pff, je pensais que tu l'avais fait :D

**Comment by ademenet** [comment]
Javais pas vu ta reponse, oui, il est pas solvable. Donc bonne nouvelle la fonction marche bien. Cest juste que javais pas compris quel input fallait lui donner en labsence de doc claire :P
Bon maintenant faut que je fasse une fonction qui deroule le tableau du coup, je pensais que ta fonction s'en occuper c'est pour ca !

**Comment by aderragui** [comment]
Ah mais je te l'avais demandé et tu m'avais "oui oui" d'un air "it's
obvious". c'est pour ça j'ai pas plus insisté

**Comment by ademenet** [comment]
Surement :D Jetais dans mon nuage
Je suis en train de voir une solution, jai pas fini... Jai eu plein de trucs qui me sont tombe dessus cet aprem.Bref, je my remets, jespere push ca avant de rentrer ce soir

**Comment by aderragui** [comment]
Ok pas de soucis. Au pre je peux le faire demain ;)

**Comment by ademenet** [comment]
Jai presque fini normalement, jai pas encore tout teste

**Comment by ademenet** [comment]
Bon jai commit un truc en pensant que ca fonctionnerait, mais maintenant il dit que tout les fichiers de test que j'ai sont insolvables. Alors qu'il devrait y en avoir au moins un de solvable dans le tas!
Jenquete !

**Comment by aderragui** [comment]
Courage !


2017-06-01 18:09 GMT+02:00 moannuo <notifications@github.com>:

**Comment by ademenet** [comment]
Question : tas fonction isSolvable renvoit un booleen cets bien ca ?
Elle renvoit true sil est solvalble et false sinon cets bien ca ?

**Comment by ademenet** [comment]
Bon a priori ca fonctionne, on a besoin de faire plus de tests, mais je marque en resolu

**Comment by aderragui** [comment]
ok cool. oui c'est bien ça : is solvable ? yes => true : no => false

2017-06-01 18:48 GMT+02:00 moannuo <notifications@github.com>:
